### ISSUE TITLE
About changing version

### ISSUE THREAD

**Issue by MeGaPk** [SDWebImage/librlottie-Xcode#1]
Please in future, dont remove already released version and dont update old version....

Because your "updating 0.1.0" just broke build, and for fix that, need to use command " rm -fr ~/.cocoapods "

**Comment by dreampiggy** [comment]
Thanks for your suggestion and I know the bad effect about `Deleting an version from CocoaPods trunk`. 😞 

Actually I have no other ways to do this, because of rlottie does not follows the semversion. By the time I release 0.1.0, they have no official 0.1.0 at all.

See more: https://github.com/SDWebImage/librlottie-Xcode#note
https://github.com/Samsung/rlottie/issues/159

**Comment by dreampiggy** [comment]
In the future, I'll always use patch version instead of minor version for custom release (Which rlottie does not provide) to avoid conflict.
